# Generated by Django 5.2.5 on 2025-08-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_premium_receipt"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-paid_at"],
                "permissions": [
                    ("pay_claim", "Peut enregistrer un remboursement de sinistre")
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="receipt",
            options={
                "ordering": ["-paid_at"],
                "permissions": [("receive_premium", "Peut encaisser une prime")],
            },
        ),
    ]
