# Generated by Django 5.2.5 on 2025-08-19 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="mime",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="attachment",
            name="size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
