# Generated by Django 5.2.5 on 2025-08-19 17:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0002_alter_attachment_mime_alter_attachment_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="claim",
            name="paid_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="claim",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
