# Generated by Django 5.2.5 on 2025-08-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("claims", "0003_claim_paid_amount_claim_paid_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="claim",
            options={
                "permissions": [
                    ("approve_claim", "Peut approuver un sinistre"),
                    ("reject_claim", "Peut rejeter un sinistre"),
                    ("mark_paid_claim", "Peut marquer payé"),
                ]
            },
        ),
    ]
