# Generated by Django 5.2.5 on 2025-08-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("underwriting", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="premium_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
