# Generated by Django 5.2.5 on 2025-08-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("underwriting", "0002_policy_premium_amount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="policy",
            options={"permissions": [("activate_policy", "Peut activer une police")]},
        ),
    ]
