# Generated by Django 5.2.5 on 2025-08-19 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_type", models.CharField(max_length=100)),
                ("object_id", models.CharField(max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("STATUS_CHANGE", "Status Change"),
                            ("IMPORT", "Import"),
                            ("REPLY", "Reply"),
                            ("PAYMENT", "Payment"),
                            ("RECEIPT", "Receipt"),
                        ],
                        max_length=20,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                ("diff", models.JSONField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-performed_at"],
                "indexes": [
                    models.Index(
                        fields=["object_type", "object_id"],
                        name="audit_audit_object__1f9df3_idx",
                    ),
                    models.Index(
                        fields=["-performed_at"], name="audit_audit_perform_f311d3_idx"
                    ),
                ],
            },
        ),
    ]
