# Generated by Django 5.2.5 on 2025-08-19 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="complaint",
            options={
                "permissions": [
                    ("answer_complaint", "Peut répondre à une plainte"),
                    ("close_complaint", "Peut clôturer une plainte"),
                ]
            },
        ),
    ]
